config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :stocks do
    resources :transactions 
  end
  

  get '/sign_up', to: 'registrations#new'

  post '/sign_up', to: 'registrations#create'

  resources :sessions, only: [:create]

  get '/sign_in', to: 'sessions#new', as: 'login'

  delete '/logout', to: 'sessions#destroy'


  get '/dashboard', to: 'stock_dashboard#dashboard'

  get '/stock_summary', to: 'stock_dashboard#summary', as: 'summary'

  get '/stock_amount', to: 'stock_dashboard#amount' , as: 'amount'

  get '/total_stocks', to: 'stock_dashboard#total_stocks'

  get '/total_amount', to: 'stock_dashboard#total_amount'

  root 'stocks#index'




  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/stock.rb
class Stock < ApplicationRecord

  belongs_to :user
  has_many :transactions, dependent: :delete_all

  validates :companyname, presence: true, length: { in: 4..50 }, uniqueness: { scope: [:companyname, :user_id] }
  validates :stockprice, presence: true, numericality: { only_integer: true, greater_than: 899, less_than: 10000000 }
  
  scope :total_purchased_amount, -> (s_id) { Stock.find(s_id).stockprice * Transaction.purchased_trans(s_id) }
  scope :total_sold_amount, -> (s_id) { Stock.find(s_id).stockprice * Transaction.sold_trans(s_id) }


  def self.total_purchased_stocks(u_id)
    purchased_stocks=0
    User.find(u_id).stocks.each do |stock|
      purchased_stocks += stock.transactions.purchased_trans(stock.id)
    end
    purchased_stocks
  end

  def self.total_sold_stocks(u_id)
    sold_stocks=0
    User.find(u_id).stocks.each do |stock|
      sold_stocks += stock.transactions.sold_trans(stock.id)
    end
    sold_stocks
  end

  def self.total_invested_amount(u_id)
    invested_amount=0
    User.find(u_id).stocks.each do |stock|
    invested_amount += Stock.total_purchased_amount(stock.id)
    end
    invested_amount
  end

  def self.total_redeemed_amount(u_id)
    redeemed_amount=0
    User.find(u_id).stocks.each do |stock|
    redeemed_amount += Stock.total_sold_amount(stock.id)
    end
    redeemed_amount
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  before_action :authorized
  before_action :set_stock, only: [:show,:edit,:update,:destroy]

  def index
    @stocks = current_user.stocks.all.paginate(page: params[:page], per_page: 4)
  end

  def new
    @stock = current_user.stocks.build
  end

  def create
    @stock = current_user.stocks.build(stock_params)
    if @stock.save
      flash[:success] = 'stock created successfully'
      redirect_to @stock
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @stock.update(stock_params)
      flash[:success] = "updated sucessfully"
      redirect_to @stock
    else
      render :edit
    end
  end

  def destroy
    @stock.destroy
    flash[:success] = "deleted successfully"
    redirect_to stocks_path
  end

  private
  def set_stock
    @stock =Stock.find(params[:id])
  end
  
  def stock_params
    params.require(:stock).permit([:companyname,:stockprice])
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb

<%= form_with(model: stock, data: { turbo: false },class: "d-grid gap-3") do |form|%>
  
  <% invalid = check_errors(@stock,:companyname) %>
  <div class="form-group">
    <%= form.label :companyname %>
    <%= form.text_field :companyname, class: "form-control #{'is-invalid' if invalid}" %>
    <%= check_valid(@stock,:companyname,invalid) %>
  </div>

  <% invalid = check_errors(@stock,:stockprice) %>
  <div class="form-group">
    <%= form.label :stockprice %>
    <%= form.number_field :stockprice, class: "form-control #{'is-invalid' if invalid}" %>
    <%= check_valid(@stock,:stockprice,invalid) %>
  </div>


  <div class="d-flex justify-content-around">
    <%= form.submit class: 'btn btn-primary' %>
    <%= back_link(stocks_path) %>
  </div>

<%end%>



app/views/stocks/edit.html.erb

<div class="d-grid gap-3 p-3 border border-dark mt-5">
  <h1>Edit Stock</h1>

  <%= render 'form', stock: @stock %>
   
</div>

app/views/stocks/index.html.erb

<div class="d-grid gap-3  mt-5 border border-dark p-3">
  <h1>Stocks of <%= current_user.username %> </h1>
  
  <div>
    <%= link_to 'Add Stock', new_stock_path, class: 'btn btn-secondary' %>
  </div>
  
  <div class="card w-100">
    <div class="card-header d-flex justify-content-between flex-wrap bg-info">
      <h3>CompanyName</h3>
      <h3 class="px-md-5">Options</h3>
    </div>
  </div>

  <% @stocks.each do |stock| %>

    <div class="card w-100">
      <div class="card-body d-flex justify-content-between flex-wrap">
        <h5 class="card-title"><%= link_to stock.companyname, stock %></h5>
        <div class="row-arrang">
          <%= show_link(stock_path(stock),'btn btn-info') %>
          <%= edit_link(edit_stock_path(stock),'btn btn-secondary') %>
          <%= delete_link(stock_path(stock),'btn btn-danger') %>
        </div>
      </div>
    </div>
    
    
  <% end %>

  <%= will_paginate @transactions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

  
</div>






app/views/stocks/new.html.erb

<div class="d-grid gap-3 p-3 border border-dark mt-5">
  <h1>Add Stock</h1>

  <%= render 'form',stock: @stock %>
</div>



app/views/stocks/show.html.erb

<div class="card text-center mt-5 border border-dark">
  <div class="card-header">
    <h3><%= link_to @stock.companyname, stock_transactions_path(@stock) %></h3>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @stock.stockprice %> stock price</p>
    <div class="d-flex justify-content-around flex-wrap row-arrang">
      <%= link_to 'transactions',stock_transactions_path(@stock), class: 'btn btn-info'%>
      <%= back_link(stocks_path) %>
    </div>
  </div>
</div>





