config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :stocks do
    resources :transactions 
  end
  

  get '/sign_up', to: 'registrations#new'

  post '/sign_up', to: 'registrations#create'

  resources :sessions, only: [:create]

  get '/sign_in', to: 'sessions#new', as: 'login'

  delete '/logout', to: 'sessions#destroy'


  get '/dashboard', to: 'stock_dashboard#dashboard'

  get '/stock_summary', to: 'stock_dashboard#summary', as: 'summary'

  get '/stock_amount', to: 'stock_dashboard#amount' , as: 'amount'

  get '/total_stocks', to: 'stock_dashboard#total_stocks'

  get '/total_amount', to: 'stock_dashboard#total_amount'

  root 'stocks#index'




  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :set_stock
  before_action :set_transaction, only: [:show,:edit,:destroy,:update]
  before_action :authorized
  
  def index
    @transactions = @stock.transactions.paginate(page: params[:page], per_page: 4)
  end

  def new
    @transaction = @stock.transactions.build
  end
  
  def create
    @transaction = @stock.transactions.build(transaction_params)
    if @transaction.save
      flash[:success] = 'transaction has been created'
      redirect_to stock_transactions_path
    else
      render :new
    end
  end

  def show; end

  def edit;	end

  def update
    if @transaction.update(transaction_params)
      flash[:success] = "updated successfully"
      redirect_to [@stock,@transaction]
    else
      render :edit
    end
  end

  def destroy
    @transaction.destroy
    if @transaction.errors.any?
      flash[:danger] = "can't delete purchased stocks can't be less than sold stocks"
      redirect_to stock_transactions_path
    else
      flash[:success] = "deleted successfully"
      redirect_to stock_transactions_path
    end
  end

  private
  def set_stock
    @stock = Stock.find(params[:stock_id])
  end

  def set_transaction
    @transaction = @stock.transactions.find(params[:id]) 
  end

  def transaction_params
    params.require(:transaction).permit([:no_of_stocks,:status])
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb

<%= form_with(model: [@stock,transaction], data: { turbo: false },class: "d-grid gap-3") do |form| %>
	

	<% invalid = check_errors(@transaction,:no_of_stocks) %>
	<div class="form-group">
		<%= form.label :no_of_stocks %>
		<%= form.number_field :no_of_stocks, class: "form-control #{'is-invalid' if invalid}" %>
		<%= check_valid(@transaction,:no_of_stocks,invalid) %>
	</div>

	<% invalid = check_errors(@transaction,:status) %>
	<div class="form-outline mb-4 row row-cols-1">
		<div class="col d-flex gap-2">
			<%= form.radio_button :status, :purchased %>
			<%= form.label :status,'purchased' %>
		</div>
		<div class="col d-flex gap-2">
			<%= form.radio_button :status, :sold %>
			<%= form.label :status,'sold' %>
		</div>	
		<%= check_valid(@transaction,:status,invalid) %>
	</div>

	<div class="d-flex justify-content-around">
		<%= form.submit  class: "btn btn-primary"  %>
		<%= back_link(stock_transactions_path([@stock])) %>
	</div>


<% end %>


app/views/transactions/edit.html.erb

<div class="d-grid gap-3 p-3 border border-dark mt-5">
  <h1>Edit a transaction</h1>
  <%= render 'form', transaction: @transaction %>
</div>



app/views/transactions/index.html.erb

<div class="d-grid gap-3  mt-5 border border-dark p-3">
  <h1>Transactions of <%= @stock.companyname%></h1>

  <div class="d-flex justify-content-around flex-wrap gap-2">
    <%= link_to "new transcation", new_stock_transaction_path(@stock,@transaction), class: 'btn btn-secondary'%> 
    <%= back_link(stock_path(@stock)) %>
  </div>
   
  <div class="card w-100">
    <div class="card-header d-flex justify-content-between flex-wrap bg-info">
      <h3 class="flex-even">Transaction</h3>
      <h3 class="flex-even">no_of_stocks</h3>
      <h3 class="flex-even ps-5">options</h3>
    </div>
  </div>


  
  <% @transactions.each do |transaction|%>
    
    <div class="card w-100">
      <div class="card-body d-flex justify-content-between flex-wrap">
        <h5 class="card-title flex-even"><%= transaction.status%></h5>
        <p class="card-text flex-even"><%= transaction.no_of_stocks%> stocks</p>
        <div class="row-arrang flex-even">
          <%= show_link([@stock,transaction],'btn btn-info') %>
          <%= edit_link(edit_stock_transaction_path(@stock,transaction),'btn btn-secondary') %>
          <%= delete_link([@stock,transaction],'btn btn-danger') %>
        </div>
      </div>
    </div>

  <% end %>
    

  <%= will_paginate @transactions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

</div>





app/views/transactions/new.html.erb

<div class="d-grid gap-3 p-3 border border-dark mt-5">
  <h1>Create a Transaction</h1>

  <%= render 'form', transaction: @transaction%>

</div>

app/views/transactions/show.html.erb
<div class="card mt-5 border border-dark">
  <h5 class="card-header"><%= @transaction.status %> transaction</h5>
  <div class="card-body">
    <h5 class="card-title"><%= @transaction.stock.companyname %></h5>
    <p class="card-text"><%= @transaction.no_of_stocks %> stocks</p>
    <%= back_link(stock_transactions_path([@stock])) %>
  </div>
</div>






