config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :stocks do
    resources :transactions 
  end
  

  get '/sign_up', to: 'registrations#new'

  post '/sign_up', to: 'registrations#create'

  resources :sessions, only: [:create]

  get '/sign_in', to: 'sessions#new', as: 'login'

  delete '/logout', to: 'sessions#destroy'


  get '/dashboard', to: 'stock_dashboard#dashboard'

  get '/stock_summary', to: 'stock_dashboard#summary', as: 'summary'

  get '/stock_amount', to: 'stock_dashboard#amount' , as: 'amount'

  get '/total_stocks', to: 'stock_dashboard#total_stocks'

  get '/total_amount', to: 'stock_dashboard#total_amount'

  root 'stocks#index'




  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Stocks",root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<%= login_helper('nav-link') %>
      </ul>
      <% if logged_in? %>
        <div class="dropdown">
          <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown"><%= current_user.username%></a>
          <div class="dropdown-menu">
          <%= link_to "Log Out", logout_path, 'data-turbo-method': :delete, class: "dropdown-item"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EquityWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= render 'layouts/header'%>

    <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %>">
          <%= msg %>
        </div>
    <% end %>
    
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-10">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>